POST https://panda-market-api.vercel.app/products/482/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTUwLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTczNDcxOTQ5MiwiZXhwIjoxNzM0NzIxMjkyLCJpc3MiOiJzcC1wYW5kYS1tYXJrZXQifQ.2SIggiW-0Tv33N6zqlwg5WT1jm3QUbaPkviPZiw8Sk8
Content-Type: application/json

{
  "content": "개굴개구리"
}