import Head from "next/head";
import "@/styles/Home.module.css";
import Header from "../../components/Header/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="content-spacer">판다마켓 랜딩페이지</div>
    </>
  );
}
